host: localhost
plugin_path: ""
tmp_path: /tmp/genom_obelix
setup: 
    - ~/.genom_env.sh

inertial:
    mass: 1.67
    Jxx: 0.015
    Jyy: 0.015
    Jzz: 0.007

geom:
    rotors: 4
    armlen: 0.23
    cf: 5.9e-4
    ct: 1e-5
    rx: 0
    rz: -1

gz:
    world: qr.world
    options: -r

components:
    rotorcraft:
        type: rotorcraft
        serial: /tmp/pty-qr
        calib: ""

    mocap:
        type: optitrack
        host: localhost
        port: "1509"

    pom:
        type: pom
        meas:
            -
                name: mocap
                port: mocap/bodies/qr
            -
                name: imu
                port: rotorcraft/imu
                offset: [0, 0, -0.075, 0, 0, 0]

    nhfc:
        type: nhfc
        gain:
            Kpxy: 15
            Kpz: 15
            Kqxy: 3
            Kqz: 3
            Kvxy: 10
            Kvz: 10
            Kwxy: 0.3
            Kwz: 0.3
            Kixy: 0
            Kiz: 0

    maneuver:
        type: maneuver
        vmax: 3
        wmax: 3
        amax: 4
        dwmax: 4

remap: {}

external_publishers: {}

sidecars: {}

ros2:
    enabled: false
    domain_id: 42
    launchfiles: []
    bag: 
