host: localhost
plugin_path: ""
tmp_path: /tmp/genom_obelix
setup: 
    - ~/.genom_env.sh
    - /opt/ros/humble/setup.bash
    - ~/work/ws_livox/ros2/install/setup.bash
    
inertial:
    mass: 1.935
    Jxx: 0.015
    Jyy: 0.015
    Jzz: 0.007

geom:
    rotors: 4
    armlen: 0.23
    cf: 5.9e-4
    ct: 1e-5
    rx: 0
    rz: -1

gz:
    world: quadrotor_lidar.world
    options: -s -r

components:
    rotorcraft:
        type: rotorcraft
        serial: /tmp/pty-qr
        calib: ""

    mocap:
        type: optitrack
        host: localhost
        port: "1509"

    pom_mocap:
        type: pom
        meas:
            -
                name: mocap
                port: mocap/bodies/qr
            -
                name: imu
                port: rotorcraft/imu
                offset: [0, 0, -0.075, 0, 0, 0]

    pom:
        type: pom
        meas:
            -
                name: lidar
                port: ros2/lio
            -
                name: imu
                port: rotorcraft/imu
                offset: [0, 0, -0.075, 0, 0, 0]

    nhfc:
        type: nhfc
        reference: maneuver/desired
        gain:
            Kpxy: 10
            Kpz: 10
            Kqxy: 15
            Kqz: 15
            Kvxy: 20
            Kvz: 20
            Kwxy: 3
            Kwz: 1
            Kixy: 0
            Kiz: 0

    maneuver:
        type: maneuver
        vmax: 3
        wmax: 3
        amax: 4
        dwmax: 4

remap: {}

external_publishers:
    lidar:
        target: pom
        publisher: measure
        port: ros2/lio

sidecars:
    lio_relay: python3 scripts/lio_relay.py qr_sim /mimosa/odometry
    rviz_bridge: python3 scripts/rviz_bridge.py qr_sim 20
    rviz: rviz2 -d ros2/config/rviz_livox.rviz > /dev/null 2>&1

ros2:
    enabled: true
    domain_id: 42
    launchfiles:
        - launch_mimosa_gz.py
    bag:
        - /mimosa/odometry
        - /mimosa/odometry_imufreq
        - /mimosa/local_map
        - /tf
        - /tf_static
        - /livox/lidar
        - /livox/imu
        - /genom/pom/odometry
        - /genom/pom_mocap/odometry
        - /genom/maneuver/desired
        - /genom/phynt/desired
