host: porche
plugin_path: /home/onepiece/devel/lib/genom/pocolibs/plugins
workspace: /home/onepiece/mjacquet/genom_obelix/
setup: 
    - ~/.onepiece.bashrc
    - /opt/ros/humble/setup.bash
    - ~/ws_ros_livox/install/setup.bash

inertial:
    mass: 3.34
    Jxx: 0.011549
    Jyy: 0.011368
    Jzz: 0.019444

geom:
    rotors: 6
    armlen: 0.39
    cf: 11.25e-4
    ct: 2.4e-5
    rx: -20
    rz: -1

components:
    rotorcraft:
        type: rotorcraft
        serial: /dev/ttyACM0
        calib: hexa2_260505.json

    mocap:
        type: qualisys
        host: 10.135.2.40

    pom_mocap:
        type: pom
        meas:
            -
                name: mocap
                port: mocap/bodies/pcHexa2
            -
                name: imu
                port: rotorcraft/imu

    pom:
        type: pom
        meas:
            -
                name: lidar
                port: ros2/lio
            -
                name: imu
                port: rotorcraft/imu
                offset: [0, 0, -0.109, 0, 0, 0]

    uavpos:
        type: uavpos
        reference: maneuver/desired
        xyradius: 2
        gain:
            Kpxy: 20
            Kpz: 20
            Kvxy: 10
            Kvz: 10
            Kixy: 0
            Kiz: 0

    uavatt:
        type: uavatt
        gain:
            Kqxy: 15
            Kqz: 15
            Kwxy: 1.5
            Kwz: 1

    maneuver:
        type: maneuver
        vmax: 1.5
        wmax: 1
        amax: 3
        dwmax: 2

    # phynt:
    #     type: phynt
    #     wo:
    #         K: [10.0, 10.0, 10.0, 2.0, 2.0, 2.0]
    #         fc: [20, 20, 20, 0, 0, 0]
    #         thresh: [0, 0, 0, 0, 0, 0]
    #         bias: [0, 0, 0, 0, 0, 0]
    #     af:
    #         K: [10, 10, 10, 100, 100, 100]

external_publishers:
    lidar:
        target: pom
        publisher: measure
        port: ros2/lio

sidecars:
    lio_relay: python3 scripts/lio_relay.py tilthex /mimosa/odometry
    rviz_bridge: python3 scripts/rviz_bridge.py tilthex 20

ros2:
    enabled: true
    domain_id: 42
    launchfiles:
        - launch_mimosa_livox.py
    bag:
        - /mimosa/odometry
        - /mimosa/odometry_imufreq
        - /mimosa/local_map
        - /tf
        - /tf_static
        - /livox/lidar
        - /livox/imu
        - /genom/pom/odometry
        - /genom/pom_mocap/odometry
        - /genom/maneuver/desired
        - /genom/phynt/desired
