/rko_lio:
    ros__parameters:
        use_sim_time: true

        imu_frame: TX/livox/base/livox_imu
        imu_topic: /livox/imu
        lidar_frame: TX/livox/base/livox_lidar
        lidar_topic: /livox/lidar

        base_frame: body_rko
        odom_frame: map
        odom_topic: /rko_lio/odometry
        map_topic: /rko_lio/local_map

        deskew: false
        double_downsample: false
        convergence_criterion: 1.0e-05
        max_iterations: 100

        max_correspondance_distance: 0.5
        max_expected_jerk: 30.0
        max_num_threads: 0
        max_points_per_voxel: 20
        max_range: 15.0
        min_range: 0.5
        min_beta: 80.0
        voxel_size: 0.5

        initialization_phase: false
        lidar_timestamps:
            multiplier_to_seconds: 0.0
            force_absolute: false
            force_relative: false
        
        invert_odom_tf: false
        publish_deskewed_scan: false
        publish_lidar_acceleration: false
        publish_local_map: true
        publish_map_after: 1.0

        # dump_results: false
        # results_dir: results
        # run_name: rko_lio_run
        # extrinsic_imu2base_quat_xyzw_xyz: []
        # extrinsic_lidar2base_quat_xyzw_xyz: []
